# This is a basic workflow to help you get started with Actions

name: Clone the config-repo of LP

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: check out another repo
        uses: actions/checkout@v2
        with:
          repository: amol-singh-by/validateLPConfig
          #path: ./cps
      - run: |
          git clone https://github.com/amol-singh-by/cps.git
          git config user.name "shreyans-gupta-by"
          git config user.email "shreyans.gupta@blueyonder.com"
          git add .
          git diff-index --quiet HEAD || git commit -m "Automatic publish from github.com/project"
          git push target master

    
    
      
