name: Push File

on: 
  push:
    branches: [ main ]
# Triggers the workflow on push or pull request events but only for the main branch

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pushes test file
      uses: amol-singh-by/validateLPConfig@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'ReadMe.md'
        destination_repo: 'amol-singh-by/cps'
        destination_folder: 'test-dir'
        user_email: 'shreyans.gupta@blueyonder.com'
        user_name: 'shreyans-gupta-by'
        commit_message: 'A custom message for the commit'
